# Generated by Django 3.2 on 2021-05-11 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('bp_problem', models.CharField(blank=True, max_length=10, null=True)),
                ('major_health_problem', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('any_operation', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
