# Generated by Django 3.2 on 2021-05-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_diseasehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasehistory',
            name='remark1',
        ),
    ]
