# Generated by Django 3.2 on 2021-05-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_diseasehistory_remark1'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='diseasehistory',
            table='account_disease_history',
        ),
    ]
