# Generated by Django 3.2 on 2021-05-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_diseasehistory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasehistory',
            options={'verbose_name_plural': 'disease_history'},
        ),
        migrations.AlterModelTable(
            name='diseasehistory',
            table=None,
        ),
    ]
