# Generated by Django 3.2 on 2021-05-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210519_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasehistory',
            options={'verbose_name_plural': 'disease history'},
        ),
    ]
