# Generated by Django 3.2 on 2021-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_diseasehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
